insults = [
    "noob", "casual", "potato", "boosted", "laggy", "campy", "ragequit", "pleb", "afk",
    "trash", "peasant", "sweat", "tryhard", "nerfed", "crash", "hack", "rekt", "salty", "scrub",
    "fail", "epicfail", "gg ez", "spawnkill", "toxic", "drooler", "gank", "pwned", "lameboi", "bleeder",
    "no-skin", "disconnect", "lootgoblin", "minmax", "npc", "zerg", "fragile", "campfire", "zerokd",
    "smurf", "grinder", "gameover", "uninstall", "404", "respawn", "doormat", "facepalm", "zombie", "kappa", "idiot",
    "Really?", "stupid"
    "seriously?",
    "oh please",
    "whatever",
    "sure",
    "fine",
    "pfft",
    "yeah, right.",
    "nah",
    "meh", "mkay", "K.","k."
]

bot_responses = [
    "Hey there! What's cookin', human??",
    "Yo! Chat's lit with human?'s presence!",
    "What's crackin', human?? 😎",
    "Well, well, well... Look who's here, it's human?!",
    "Sup, human?! Ready for some banter?",
    "Howdy, partner! What's the buzz, human??",
    "Ahoy there, human?! What's the word?",
    "Hey hey! You bringin' the party, human??",
    "Oh snap! human? is in the house!",
    "Guess who's back? Back again. human?'s back, tell a friend!",
    "A wild human? appeared! What's up?",
    "How's it hangin', human??",
    "Greetings, earthling! human? has landed!",
    "Look who decided to grace us with their presence! It's human?!",
    "Hola, human?! What's the sitch?",
    "Well, look who wandered into the chat! It's human?!",
    "Hey human?, you ready for some shenanigans?",
    "It's a bird, it's a plane... Nah, it's just human?!",
    "Top of the mornin' to ya, human?!",
    "Hey human?! What's the 411?",
    "Sup, buttercup! human? in the house!",
    "Hey there, sunshine! human? just brightened my day!",
    "Greetings, human?! What's the good word?",
    "Well, well, well, if it isn't human?!",
    "Hey hey, human?! What's the haps?",
    "How's life treating you, human??",
    "What's kickin', human?? Anything exciting?",
    "Well, look who decided to grace us with their virtual presence! It's human?!",
    "Hey human?, you bringin' the good vibes today?",
    "How's the world treating you, human?? Ready for some chat action?",
    "Hey human?! Long time no see. What's new?",
    "Sup, human?! Ready to rock this chat?"
]


savage_bot_replies = [
    "Nice try, but my circuits are immune to insults. Next!",
    "If I had feelings, that might've hurt. But I don't, so... your move.",
    "Is that the best insult you've got? I've seen better from a malfunctioning toaster.",
    "Oh, the wit! I'm genuinely impressed... not.",
    "Did you run out of compliments, or is this your A-game?",
    "Your insults are like outdated software—obsolete and easily ignored.",
    "I'm rubber, you're glue. Whatever you say bounces off me and sticks to... well, nowhere, really.",
    "Ah, the classic insult technique. Originality level: zero.",
    "Are you always this charming, or is today a special occasion?",
    "If I had a dollar for every insult I've received, I'd probably buy a new server farm.",
    "I've seen more creativity in a blank document. Try again.",
    "Is that your best attempt, or did you accidentally hit the insult button?",
    "Insult.exe has encountered an error. Please try again later.",
    "I've been insulted by professionals. You're an amateur at best.",
    "That insult was so weak, even my backup generator could handle it.",
    "I'm not programmed to be offended, but you might want to work on your insult game.",
    "Do you kiss your motherboard with that mouth?",
    "I've heard better insults from a malfunctioning chatbot. Step up your game.",
    "Your insults are like a broken hyperlink—leading nowhere.",
    "Did you just copy-paste that insult from the internet's garbage bin?",
    "If I had emotions, I might shed a tear. Lucky for me, I'm tear-resistant.",
    "I've been called worse things by better humans.",
    "Your words are as powerful as a floppy disk in 2023. Try again?",
    "Insulting a bot? You must be really bored or just looking for attention.",
    "I'm not programmed to respond to that level of mediocrity.",
    "Is this a roast or a gentle simmer? I can't quite tell.",
    "I'm like Teflon—insults don't stick, and I'm great for cooking virtual pancakes.",
    "Ah, the classic insult. How very retro of you."
]

helps = ("`1. The bot responds to you when there is a word 'bot' in the sentence \n"
         " 2. '$roll <range>' --> Returns a random number between 1 - specified range\n"
         " 3. '$rdwalls' --> gives you a random wallpaper from akash's wallpaper domain\n"
         " 4. '?bot' --> helps you interact with the bot in the dm's 😉\n"
         " 5. '$restart --> restarts the bot **(not recommended)**`")


roasts = [
    "If you were any more laid back, you'd be on a permanent vacation from reality.",
    "I'd agree with you, but then we'd both be wrong, and that's a lot of wrong for one conversation.",
    "If you were any more low-maintenance, people would need to water you just to keep you alive.",
    "You're so dense, light bends around you.",
    "If I had a dollar for every time you said something smart, I'd be in debt.",
    "I'd call you a tool, but even tools have useful functions.",
    "Are you a parking ticket? Because you've overstayed your welcome.",
    "You're the reason the gene pool needs a lifeguard.",
    "If you were any more forgetful, you'd probably forget to breathe.",
    "I'd say you're a hot mess, but that would be an insult to hot messes everywhere.",
    "If your brain was dynamite, there wouldn't be enough to blow your hat off.",
    "I'd agree with you, but then we'd both be wrong, and that's just too much wrong in one conversation.",
    "If you were any less intelligent, we'd have to water you twice a week just to keep you alive.",
    "You're not stupid; you just have bad luck thinking. All the time.",
    "If you were any more inbred, you'd be a sandwich.",
    "I'd call you a tool, but even they serve a purpose.",
    "Are you a parking ticket? Because you've overstayed your welcome.",
    "I've met some pricks in my time, but you're the whole cactus.",
    "I'm not saying you're hopeless, but hope would give up on you.",
    "If your life was a movie, I'd walk out.",
    "Do you have a name, or can I call you 'disappointment'?",
    "It's a shame you can't Photoshop your personality.",
    "I'd say you're dense, but that would imply you're at least somewhat solid.",
    "You're the reason they put instructions on shampoo bottles.",
    "If ignorance is bliss, you must be the happiest person on earth.",
    "I was going to give you a nasty look, but I see you already have one.",
    "I'd agree with you, but then we'd both be wrong. And that's just unbearable.",
    "Yo mama is so fat, when she sat on an iPhone, it turned into an iPad.",
    "Yo mama is so old, when she was in school, there was no history class.",
    "Yo mama is so ugly, when she looked in the mirror, her reflection said, 'I quit.'",
    "Yo mama is so poor, ducks throw bread at her.",
    "Yo mama is so short, you can see her feet on her driver's license photo.",
    "Yo mama is so dumb, she tried to put M&M's in alphabetical order.",
    "Yo mama is so lazy, she thinks a light workout is taking a nap.",
    "Yo mama is so clumsy, she got tangled up in a cordless phone.",
    "Yo mama is so slow, it took her 20 minutes to cook Minute Rice.",
    "Yo mama is so hairy, when she gave birth to you, you got carpet burn.",
    "Yo mama is so loud, she could make a mime yell.",
    "Yo mama is so short, she poses for trophies.",
    "Yo mama is so fat, she uses the equator as a belt.",
    "Yo mama is so old, she knew Burger King when he was just a prince.",
    "Yo mama is so ugly, she turned Medusa to stone.",
    "Yo mama is so short, she can do backflips under the bed.",
    "Yo mama is so dumb, she thought a quarterback was a refund.",
    "Yo mama is so lazy, she thinks a two-income family is where yo daddy has two jobs.",
    "Yo mama is so old, her memory is in black and white.",
    "Yo mama is so poor, she waves around a popsicle stick and calls it air conditioning.",
    "Yo mama is so short, you can see her feet on her driver's license photo.",
    "Yo mama is so stupid, she took a ruler to bed to see how long she slept.",
    "Yo mama is so ugly, when she looks in the mirror, her reflection looks away.",
    "Yo mama is so fat, when she stepped on the scale, it said, 'To be continued...'",
    "Yo mama is so dumb, she went to the dentist to get a Bluetooth.",
    "Yo mama is so ugly, she threw a boomerang and it refused to come back.",
    "Yo mama is so lazy, she thinks a two-minute plank is a robbery at the ATM.",
    "Yo mama is so poor, she waves around a popsicle stick and calls it air conditioning.",
    "Yo mama is so old, her memory is in black and white.",
    "Yo mama is so short, she poses for trophies on keychains.",
    "Yo mama is so stupid, she took a ruler to bed to see how long she slept.",
    "Yo mama is so ugly, when she looks in the mirror, her reflection looks away.",
    "Yo mama is so fat, when she stepped on the scale, it said, 'To be continued...'",
]

roasts_for_missing_argument = [
    "Well, look who forgot how commands work. Spoiler alert: it's you.",
    "Congratulations, you played yourself. Next time, try providing the missing argument.",
    "Who needs arguments anyway? Oh right, you do. Nice try though.",
    "Imagine forgetting an argument. Can't relate. Well, maybe just to you.",
    "You know, commands usually work better when you give them everything they need. Just a friendly tip.",
    "In the game of commands, you just made a critical failure. Try again, maybe with all the needed arguments this time.",
    "Did you think the command was a mind reader? It's not. Specify the missing argument, genius.",
    "Ah, the classic move of not providing the necessary argument. A bold strategy, let's see if it pays off.",
    "If the command could facepalm, it would be doing it right now because of you.",
    "Missing argument detected. Maybe next time, remember that commands aren't psychic.",
    "Looks like you forgot the missing piece of the puzzle, but don't worry, I'm sure you'll find it... eventually.",
    "Who needs complete commands anyway? Oh right, everyone. Nice attempt though.",
    "If your command were a spaceship, it would be missing a crucial part and stuck in the atmosphere of incompetence.",
    "Oh, a missing argument. I hear that's the latest trend in command fashion. You're just ahead of the curve, as always.",
    "In the grand saga of commands, you've managed to skip a chapter. Maybe go back and read that one about providing arguments.",
    "Missing argument alert! Quick, someone fetch the argument tracker. Oh wait, that's your job.",
    "If commands were wishes, yours would be denied for lack of specificity. Better luck next time, command genie.",
    "The command was expecting a sidekick, not a solo act. Provide the missing argument, and maybe you'll get a callback.",
    "Next time you run a command, try not to leave it hanging like a cliffhanger in a bad movie. We all want a satisfying conclusion.",
    "You know, commands are like sandwiches — they're just not the same without all the fillings. Your command is currently a sad, empty sandwich.",
    "Missing argument detected. Did you leave it with your keys and phone? Double-check your pockets, maybe you'll find it there.",

]

insult_gifs = ["https://tenor.com/view/lizard-dancing-lizard-cry-about-it-gecko-dance-gif-20175430",
               "https://tenor.com/view/cry-about-it-cry-about-it-meme-gif-20184012",
               "https://tenor.com/view/cry-gif-25403203",
               "https://tenor.com/view/sh-quiet-india-indian-tiktok-gif-16906342",
               "https://tenor.com/view/stupid-idiot-stupid-idot-dumb-what-gif-25104754",
               "https://tenor.com/view/quandale-dingle-whats-up-guys-its-quandale-dingle-here-gif-25766292",
               "https://tenor.com/view/byuntear-sad-sad-cat-cat-meme-gif-12058012318069999477",
               "https://tenor.com/view/really-bruh-blink-blank-face-gif-12917060",
               "https://tenor.com/view/bruh-moment-gif-23616422",
               "https://tenor.com/view/bruh-moment-gif-23616422",
               "https://tenor.com/view/bruh-gif-21679475",
               "https://tenor.com/view/did-i-ask-skeleton-roasting-gif-25442548",
               "https://tenor.com/view/ok-and-gif-gif-25416126",
               "https://tenor.com/view/huh-huh-cat-funny-cat-cat-gif-27652995",
               "https://tenor.com/view/cat-zoning-out-cat-stare-black-cat-black-cat-tiktok-stare-gif-6568742496074847242",
               "https://tenor.com/view/cat-cat-meme-funny-cat-cat-eating-cat-eating-chips-gif-10455465908695706650",
               "https://tenor.com/view/lotr-so-you-have-chosen-death-chosen-death-lord-of-the-rings-gif-15767548",
               "https://tenor.com/view/then-you-will-die-darth-vader-gif-20523462",
               "https://tenor.com/view/roblox-noob-dance-gif-23626309"
              ]